# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IceCreamCalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



#Input from qt desginer
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(300, 0, 221, 51))
        self.name_label.setObjectName("name_label")
        self.cone_label = QtWidgets.QLabel(self.centralwidget)
        self.cone_label.setGeometry(QtCore.QRect(30, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cone_label.setFont(font)
        self.cone_label.setObjectName("cone_label")
        self.ice_cream_sandwich_label = QtWidgets.QLabel(self.centralwidget)
        self.ice_cream_sandwich_label.setGeometry(QtCore.QRect(30, 160, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.ice_cream_sandwich_label.setFont(font)
        self.ice_cream_sandwich_label.setObjectName("ice_cream_sandwich_label")
        self.soft_serve_label = QtWidgets.QLabel(self.centralwidget)
        self.soft_serve_label.setGeometry(QtCore.QRect(30, 250, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.soft_serve_label.setFont(font)
        self.soft_serve_label.setObjectName("soft_serve_label")
        self.cone_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cone_lineEdit.setGeometry(QtCore.QRect(400, 90, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cone_lineEdit.setFont(font)
        self.cone_lineEdit.setObjectName("cone_lineEdit")
        self.sandwich_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sandwich_lineEdit.setGeometry(QtCore.QRect(400, 170, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.sandwich_lineEdit.setFont(font)
        self.sandwich_lineEdit.setObjectName("sandwich_lineEdit")
        self.soft_serve_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.soft_serve_lineEdit.setGeometry(QtCore.QRect(400, 270, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.soft_serve_lineEdit.setFont(font)
        self.soft_serve_lineEdit.setObjectName("soft_serve_lineEdit")
        self.calculate_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(210, 320, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.calculate_button.setFont(font)
        self.calculate_button.setObjectName("calculate_button")

        #Connecting the button to the calculation def

        self.calculate_button.clicked.connect(self.calculate_total)
        self.total_price = QtWidgets.QLabel(self.centralwidget)
        self.total_price.setGeometry(QtCore.QRect(400, 400, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.total_price.setFont(font)
        self.total_price.setText("")
        self.total_price.setObjectName("total_price")
        self.total_price_label = QtWidgets.QLabel(self.centralwidget)
        self.total_price_label.setGeometry(QtCore.QRect(120, 400, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.total_price_label.setFont(font)
        self.total_price_label.setObjectName("total_price_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "Ice Cream Shop"))
        self.cone_label.setText(_translate("MainWindow", "$3.00 Cone"))
        self.ice_cream_sandwich_label.setText(_translate("MainWindow", "$4.00 Ice Cream Sandwich"))
        self.soft_serve_label.setText(_translate("MainWindow", "$2.00 Soft Serve"))
        self.calculate_button.setText(_translate("MainWindow", "Check Out"))
        self.total_price_label.setText(_translate("MainWindow", "Total Price:"))
#Assigning variables to the user input then multiplying the user input by the price of each item
#adding them and then displaying the result.
    def calculate_total(self):
        cone = float(self.cone_lineEdit.text())*3
        ice_cream_sandwich = float(self.sandwich_lineEdit.text())*4
        soft_serve = float(self.soft_serve_lineEdit.text())*2
        result = cone+ice_cream_sandwich+soft_serve
        self.total_price.setText(str(result))
#Running the application
if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())